:PROPERTIES:
:ID:       4E406635-5849-42C9-8064-8E5DA0DBECEF
:END:
#+title: S3 Security
#+tags: [[id:408B7225-BAE3-4B4B-B1E8-C12C831563B0][Associate Shared]]

* S3 Security
S3 is private by default. Only the account root user have initial access to the bucket. Anything else must be EXPLICITLY GRANTED.

** S3 Bucket Policies
Type of a resource policy which are like identity policies but only attached to AWS resources instead of identities. Basically controlling who can access that resource.

Bucket policies can ~ALLOW~ or ~DENY~ from the same account or different accounts because the policy is attached to the resource.

It can also reference any other identities inside the policy.

Can ~ALLOW~ or ~DENY~ anonymous principals.

#+begin_src js
  {
      "Version": "2012-10-17",
      "Statement": [
          "Sid": "PublicRead",
          "Effect": "Allow",
          "Principal": "*",
          // applies to anyone accssing the bucket
          "Action": ["s3:GetObject"],
          "Resource": ["arn:aws:s3:::secretcatproject/*"]
      ]
  }
#+end_src

With resource policies, the ~Principal~ is explicitly defined. It defines which principals are affected by the policy.

Another example:
#+begin_src js
  {
      "Version": "2012-10-17",
      "Id": "BlockUnLeet"
      "Statement": [
          "Sid": "IPAllow",
          "Effect": "Deny",
          "Principal": "*",
          // applies to anyone accssing the bucket
          "Action": "s3:*"
          "Resource": "arn:aws:s3:::secretcatproject/*",
          // condition block only applies if the body is True
          "Condition": {
              "NotIPAddress": {"aws:SourceIP": "1.3.3.7/32"}
          }
      ]
  }
#+end_src

There can only be 1 bucket policy in a bucket but it can have multiple statements.

* Access Control Lists (ACL)
A way to apply security to objects or buckets.

It is a subresource and is legacy.

Inflexible & simple permissions.

| Permission   | Bucket                                                     | Object                                                     |
|--------------+------------------------------------------------------------+------------------------------------------------------------|
| READ         | Allows listing of objects in a bucket                      | Allows grantee to read the object data and its metadata.   |
| WRITE        | Create, overwrite, and delete any object in the bucket     | -                                                          |
| READ_ACP     | Read the bucket ACL                                        | Read the bucket ACL                                        |
| WRITE_ACP    | Write the ACL for the applicable bucket                    | Write ACL for the applicable bucket                        |
| FULL CONTROL | READ, WRITE, READ_ACP, WRITE_ACP permissions on the bucket | READ, WRITE, READ_ACP, WRITE ACP permissions on the object |

* Block Public Access
Added another level of security which are the *Block Public Access Settings* which apply no matter what the bucket policies say.

Just applied on the public access.
