:PROPERTIES:
:ID:       A19A4254-E4C4-49AF-A127-C07F09F6BC97
:END:
#+title: CloudTrail Essentials
#+tags: [[id:408B7225-BAE3-4B4B-B1E8-C12C831563B0][Associate Shared]]

* Table of Contents :toc:
- [[#cloudtrail][CloudTrail]]
- [[#cloudtrail-events-types][CloudTrail Events Types]]
  - [[#management-events][Management Events]]
  - [[#data-events][Data Events]]
  - [[#insight-events][Insight Events]]
- [[#cloudtrail-trail][CloudTrail Trail]]
  - [[#organizational-trail][Organizational Trail]]

* CloudTrail
Logs API actions which affect AWS accounts. These logs are called as ~CloudTrail Event~.

By default, stores the last *90 days* of CloudTrail events in ~Event History~. This is enabled by default and there is no cost for the 90 day history.

CloudTrail is NOT REALTIME. There is a delay is within 15 minutes of the account activiy occuring before the log files are delivered.

* CloudTrail Events Types
By default, only logs management events.

** Management Events
Provide information on management operation that are performed on resources on the account. Also known as *control pane operations*.

** Data Events
Contain information on resource operations performed on/in a resource.

Much higher volume than management events.

** Insight Events

* CloudTrail Trail
The unit of configuration on a CloudTrail product.

~Trail~ logs events for the AWS region that is created in. We can however create a trail which is a ~one region trail~ or can be set to *all regions.*

Logs generated by AWS services that are global are classified as *global service events*. They log to us-east-1. The trail needs to be enabled to be able log events that are global.

Once a trail is created, management and data events are captured by the trail.

By default, a trail can store events in a definable S3 bucket as a set of *compressed JSON log files*. It can be stored there indefinitely.

** Organizational Trail
Creating this in the management account of an organization, it can store all the information for all of the accounts in that organization.
